### ISSUE TITLE
ONIOM energy 

### ISSUE THREAD

**Issue by lmoranglez** [maserasgroup-repo/pyssian#3]
Hi Raúl, 
Just as a suggestion:
It might be not feasible to include it, but pyssian might have a function to detect the ONIOM calculation and print the correct ONIOM energy with pyssian-thermo.py (instead of the "Done energy" which refers to the QM layer). 

**Link 120** is the one that controls the ONIOM calculations

The first ONIOM word of the file: 
(_Enter /mnt/data/applications/G16/g16/l120.exe)
 ONIOM: Cut between C /H    23 and C    20 factor= 0.723886 0.723886
 ONIOM: Cut between C /H    25 and C    22 factor= 0.723886 0.723886
 ONIOM: Cut between N /H    35 and P    34 factor= 0.826858 0.826858
 ONIOM: Cut between N /H    36 and P    34 factor= 0.826858 0.826858
 ONIOM: Cut between O /H    37 and P    34 factor= 0.856464 0.856464
 ONIOM: saving gridpoint 17
 ONIOM: generating point  3 -- low level on real system.
 Leave Link  120 at Sun Jun  6 23:20:16 2021, MaxMem= 14763950080 cpu:               0.1 elap:               0.0_

And in the final Link 120 appears the ONIOM energy value. To find it just: 
_$grep "ONIOM: extrapolated" ONIOM_file.out | tail -n 1_

The ZPE, H and G are properly printed. 

Thanks, 
Lucía

**Comment by rperezsoto** [comment]
Added a Link120 parser that stores the extrapolated energy and the energies of the different layers and models
